Repository ahmedheakl/multi-level-rl-for-robotics, pull requests merged in 2023-02, with the labels that each got.

#11 Feat/refactor
  .coverage
  .github/workflows/build.yml
  .github/workflows/test.yml
  .gitignore
  MANIFEST
  docs/source/conf.py
  lidar2d_fast.cpp
  lidar2d_fast.html
  pyproject.toml
  requirements.txt
  src/highrl/__init__.py
  src/highrl/__main__.py
  src/highrl/agents/__init_.py
  src/highrl/agents/agent.py
  src/highrl/agents/robot.py
  src/highrl/callbacks/__init.py
  src/highrl/callbacks/__init__.py
  src/highrl/callbacks/robot_callback.py
  src/highrl/callbacks/teacher_callback.py
  src/highrl/configs/colors.py
  src/highrl/configs/configurations.py
  src/highrl/envs/env_encoders.py
  src/highrl/envs/eval_env.py
  src/highrl/envs/robot_env.py
  src/highrl/envs/teacher_env.py
  src/highrl/graphs/model_training_plot_styles.py
  src/highrl/obstacle/__init__.py
  src/highrl/policy/feature_extractors.py
  src/highrl/policy/policy_networks.py
  src/highrl/utils/action.py
  src/highrl/utils/calculations.py
  src/highrl/utils/human.py
  src/highrl/utils/parser.py
  src/highrl/utils/teacher_checker.py
  src/lidar2d_fast.cpython-38-x86_64-linux-gnu.so
  test/test_plannerchecker.py
  test/test_teacherchecker.py
Labels: bug, enhancement

#12 Bump the version
  .github/workflows/build.yml
  Guidelines.md
  lidar2d_fast.cpp
  lidar2d_fast.html
  mypy.ini
  pyproject.toml
  src/highrl/__init__.py
  src/highrl/__main__.py
Labels: bug

#13 Fix/version
  .github/pull_request_template.md
  .github/workflows/build.yml
  .github/workflows/test.yml
  .gitignore
  Guidelines.md
  docs/source/conf.py
  lidar2d_fast.cpp
  lidar2d_fast.html
  mypy.ini
  pyproject.toml
  requirements.txt
  src/highrl/__init__.py
  src/highrl/__main__.py
  src/highrl/agents/agent.py
  src/highrl/agents/robot.py
  src/highrl/callbacks/__init__.py
  src/highrl/callbacks/robot_callback.py
  src/highrl/callbacks/teacher_callback.py
  src/highrl/configs/colors.py
  src/highrl/configs/configurations.py
  src/highrl/envs/env_encoders.py
  src/highrl/envs/robot_env.py
  src/highrl/envs/teacher_env.py
  src/highrl/graphs/model_training_plot_styles.py
  src/highrl/policy/feature_extractors.py
  src/highrl/policy/policy_networks.py
  src/highrl/utils/action.py
  src/highrl/utils/calculations.py
  src/highrl/utils/human.py
  src/highrl/utils/parser.py
  src/highrl/utils/teacher_checker.py
  src/lidar2d_fast.cp310-win_amd64.pyd
  src/lidar2d_fast.cpython-39-x86_64-linux-gnu.so
  test/test_teacherchecker.py
Labels: bug

#14 Release
  MANIFEST.in
  pyproject.toml
  src/highrl/agents/__init_.py
  src/highrl/configs/__init__.py
Labels: bug

#15 Feat/tensorboard
  requirements.txt
  src/highrl/configs/configurations.py
  src/highrl/envs/robot_env.py
  src/highrl/envs/teacher_env.py
  src/highrl/policy/policy_networks.py
Labels: bug, enhancement

#18 Fix/refactor
  .github/workflows/build.yml
  .gitignore
  pyproject.toml
  src/highrl/__init__.py
  src/highrl/__main__.py
  src/highrl/agents/agent.py
  src/highrl/callbacks/robot_callback.py
  src/highrl/callbacks/teacher_callback.py
  src/highrl/configs/configurations.py
  src/highrl/envs/eval_env.py
  src/highrl/envs/robot_env.py
  src/highrl/envs/teacher_env.py
  src/highrl/obstacle/obstacles.py
  src/highrl/obstacle/single_obstacle.py
  src/highrl/utils/calculations.py
  src/highrl/utils/parser.py
  src/highrl/utils/robot_utils.py
  src/highrl/utils/teacher_checker.py
  src/highrl/utils/teacher_utils.py
  src/highrl/utils/training_utils.py
  src/highrl/utils/utils.py
  test/test_teacherchecker.py
Labels: help wanted

#19 Feat/logger
  .coverage
  .github/workflows/build.yml
  .gitignore
  pyproject.toml
  src/highrl/__init__.py
  src/highrl/__main__.py
  src/highrl/agents/agent.py
  src/highrl/callbacks/robot_callback.py
  src/highrl/callbacks/teacher_callback.py
  src/highrl/envs/env_player.py
  src/highrl/envs/robot_env.py
  src/highrl/envs/teacher_env.py
  src/highrl/graphs/plot_using_averages.py
  src/highrl/graphs/plot_using_max_of_points.py
  src/highrl/graphs/plot_using_min_of_points.py
  src/highrl/graphs/plot_using_smoothing.py
  src/highrl/lidar_setup/rings.py
  src/highrl/utils/general.py
  src/highrl/utils/logger.py
  src/highrl/utils/robot_utils.py
  src/highrl/utils/teacher_checker.py
  src/highrl/utils/teacher_utils.py
  src/highrl/utils/training_utils.py
Labels: documentation, enhancement

#20 Fix: Replacing List instances with Position
  src/highrl/agents/__init_.py
  src/highrl/agents/agent.py
  src/highrl/agents/robot.py
  src/highrl/envs/robot_env.py
  src/highrl/utils/__init__.py
  src/highrl/utils/abstract.py
  src/highrl/utils/calculations.py
  src/highrl/utils/general.py
  src/highrl/utils/robot_utils.py
  src/highrl/utils/teacher_checker.py
  src/highrl/utils/teacher_utils.py
  test/test_agent.py
  test/test_calculations.py
  test/test_obstacles.py
  test/test_teacherchecker.py
Labels: enhancement

#22 Fix: Append Method
  .github/workflows/build.yml
  pyproject.toml
  src/highrl/__init__.py
  src/highrl/__main__.py
  src/highrl/callbacks/robot_callback.py
  src/highrl/configs/configurations.py
  src/highrl/envs/robot_env.py
  src/highrl/envs/teacher_env.py
  src/highrl/utils/abstract.py
  src/highrl/utils/teacher_checker.py
Labels: enhancement
